package view;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Area;
import model.AreaDao;
import model.AreaFormacao;
import model.AreaFormacaoDao;


/**
 *
 * @author Clayd Nandza
 */

public class InternalArea extends javax.swing.JInternalFrame {
    AreaDao areaDao = new AreaDao();
    AreaFormacaoDao areaforDao = new AreaFormacaoDao();
    
    
    /**
     * Creates new form Ramo
     */
    public InternalArea() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
    
        BasicInternalFrameUI basicInternalFrameUi =(BasicInternalFrameUI)this.getUI();
        basicInternalFrameUi.setNorthPane(null);  
        
        preencherTabela(areaDao.listar());
        this.btnEliminar.setEnabled(false);
        jtfId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTrabalho = new javax.swing.JLabel();
        jtfRamos = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabAreas = new javax.swing.JTable();
        jtfId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTrabalho1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfAreaFormacao = new javax.swing.JTextField();
        btnAdicionar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabAreasFor = new javax.swing.JTable();
        boxRamos = new javax.swing.JComboBox<>();
        jtfId1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        lblTrabalho.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        lblTrabalho.setText("Ramo");
        lblTrabalho.setPreferredSize(new java.awt.Dimension(80, 25));

        btnAdicionar.setFont(new java.awt.Font("Sitka Display", 0, 15)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/plus_math_24px.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setPreferredSize(new java.awt.Dimension(85, 30));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Sitka Display", 0, 15)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/delete_trash_24px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setPreferredSize(new java.awt.Dimension(85, 30));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tabAreas.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        tabAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Ramo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabAreasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabAreas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jtfRamos, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRamos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, 390));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 45)); // NOI18N
        jLabel1.setText("Cadastrar Ramo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 324, 45));

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        lblTrabalho1.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        lblTrabalho1.setText("Especialidade");
        lblTrabalho1.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        jLabel4.setText("Ramo");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 25));

        btnAdicionar1.setFont(new java.awt.Font("Sitka Display", 0, 15)); // NOI18N
        btnAdicionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/plus_math_24px.png"))); // NOI18N
        btnAdicionar1.setText("Adicionar");
        btnAdicionar1.setPreferredSize(new java.awt.Dimension(85, 30));
        btnAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setFont(new java.awt.Font("Sitka Display", 0, 15)); // NOI18N
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/delete_trash_24px.png"))); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setPreferredSize(new java.awt.Dimension(85, 30));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        tabAreasFor.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        tabAreasFor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Ramo", "Area de Formacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabAreasFor);

        boxRamos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTrabalho1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfAreaFormacao)
                    .addComponent(boxRamos, 0, 240, Short.MAX_VALUE))
                .addGap(518, 518, 518))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfId1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jtfId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfAreaFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTrabalho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxRamos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 143, 450, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
           try{
            if(jtfRamos.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Prencha o espaco"," Atencao",INFORMATION_MESSAGE);
            } else  {
                 Area area = new Area();
                 AreaDao areaDao = new AreaDao();
                 area.setArea(jtfRamos.getText());
                 areaDao.salvar(area);
                 jtfRamos.setText(" ");
                 preencherTabela(areaDao.listar());
            }
        } catch (Exception ex) {
            Logger.getLogger(InternalArea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int retorno = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente eliminar?");
        if (retorno ==JOptionPane.OK_OPTION){
           try {
               Area area = new Area();
               AreaDao areaforDao = new AreaDao();
               areaforDao.eliminar(Area.class, Long.parseLong(jtfId.getText()));
               JOptionPane.showConfirmDialog(null, "Apagado com sucesso","", JOptionPane.DEFAULT_OPTION, 1);   
               preencherTabela(areaforDao.listar());
               jtfRamos.setText("");
           } catch (HeadlessException | NumberFormatException ex) {
           }
            
        } else {
            JOptionPane.showConfirmDialog(null, "Nenhum item foi selecionado","", JOptionPane.DEFAULT_OPTION, 1);   
        } 
         btnAdicionar.setEnabled(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tabAreasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabAreasMouseClicked
        int i = tabAreas.getSelectedRow();
        TableModel model3 = tabAreas.getModel();
        jtfRamos.setText((String) model3.getValueAt(i, 1));
        btnAdicionar.setEnabled(false);
        btnEliminar.setEnabled(true);
        
    }//GEN-LAST:event_tabAreasMouseClicked

    private void btnAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar1ActionPerformed
        try{
            if(jtfAreaFormacao.getText().isEmpty() || boxRamos.getSelectedIndex()==-1){
                JOptionPane.showMessageDialog(null,"Prencha o espaco"," Atencao",INFORMATION_MESSAGE);
            } else  {
                AreaFormacao areafor = new AreaFormacao();
                AreaFormacaoDao areafordao = new AreaFormacaoDao();
                areafor.setArea(boxRamos.getSelectedItem().toString());
                areafor.setEspecilidade(jtfAreaFormacao.getText());
                areafordao.salvar(areafor);
                preencherTabelaFor(areafordao.listar());
            }
        } catch (Exception ex) {
            Logger.getLogger(InternalAreaFormacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        int retorno = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente eliminar?");
        if (retorno ==JOptionPane.OK_OPTION){
            try {
                AreaFormacao area = new AreaFormacao();
                AreaFormacaoDao areaformacaoDao = new AreaFormacaoDao();
                areaformacaoDao.eliminar(AreaFormacao.class, Long.parseLong(jtfId.getText()));
                JOptionPane.showConfirmDialog(null, "Apagado com sucesso","", JOptionPane.DEFAULT_OPTION, 1);

                preencherTabelaFor(areaformacaoDao.listar(area));
                jtfAreaFormacao.setText("");
                boxRamos.setSelectedIndex(0);
            } catch (HeadlessException | NumberFormatException ex) {
            }

        } else {
            JOptionPane.showConfirmDialog(null, "Nenhum item foi selecionado","", JOptionPane.DEFAULT_OPTION, 1);
        }
        btnAdicionar.setEnabled(true);
    }//GEN-LAST:event_btnEliminar1ActionPerformed
 
  
    private void preencherTabela(List<Area> areas){
         DefaultTableModel model = new DefaultTableModel();
         tabAreas.setModel(model);
         model.addColumn("ID");
         model.addColumn("Ramo");
         tabAreas.getColumnModel().getColumn(0).setPreferredWidth(10);
         
         for(Area area : areas){
         model.addRow(new Object[]{ area.getId(), area.getArea()});
         }
     }
     private void preencherCombo(){
        ArrayList<Area> lista = new ArrayList<Area>();
        lista = areaDao.listar();
    
        boxRamos.removeAllItems();
        boxRamos.addItem(null);
    
        for (Area area : lista){
            boxRamos.addItem(area.toString());
        }
    }
    
    public void preencherTabelaFor(List<AreaFormacao> areasFormacao){
         DefaultTableModel model = new DefaultTableModel();
         tabAreasFor.setModel(model);
         model.addColumn("ID");
         model.addColumn("Ramo");
         model.addColumn("Area de Formacao");
         tabAreasFor.getColumnModel().getColumn(0).setPreferredWidth(10);
         
         for(AreaFormacao areaFormacao : areasFormacao){
         model.addRow(new Object[]{ areaFormacao.getId(), areaFormacao.getArea(), areaFormacao.getEspecilidade()});
         }
     }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxRamos;
    public javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAdicionar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtfAreaFormacao;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfId1;
    private javax.swing.JTextField jtfRamos;
    private javax.swing.JLabel lblTrabalho;
    private javax.swing.JLabel lblTrabalho1;
    private javax.swing.JTable tabAreas;
    private javax.swing.JTable tabAreasFor;
    // End of variables declaration//GEN-END:variables
}
