package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Candidato;
import model.CandidatosDao;
import model.DAO;

/**
 *
 * @author Clayd Nandza
 */
public class InternalVirtude extends javax.swing.JInternalFrame {

    /**
     * Creates new form Virtude
     */
    public InternalVirtude() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI basicInternalFrameUi =(BasicInternalFrameUI)this.getUI();
        basicInternalFrameUi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkDisponibilidade = new javax.swing.JCheckBox();
        checkEquipa = new javax.swing.JCheckBox();
        checkPressao = new javax.swing.JCheckBox();
        checkDinamismo = new javax.swing.JCheckBox();
        checkMSOffice = new javax.swing.JCheckBox();
        checkAdaptacaco = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(940, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Condensed", 2, 30)); // NOI18N
        jLabel1.setText("Virtudes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(408, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(435, 435, 435))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/skills.png"))); // NOI18N

        checkDisponibilidade.setBackground(new java.awt.Color(255, 255, 255));
        checkDisponibilidade.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkDisponibilidade.setText("Disponibilidade Imediata");
        checkDisponibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDisponibilidadeActionPerformed(evt);
            }
        });

        checkEquipa.setBackground(new java.awt.Color(255, 255, 255));
        checkEquipa.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkEquipa.setText("Capacidade de Trabalhar em Equipa");
        checkEquipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEquipaActionPerformed(evt);
            }
        });

        checkPressao.setBackground(new java.awt.Color(255, 255, 255));
        checkPressao.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkPressao.setText("Capacidade de Trabalhar sob Pressão");
        checkPressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPressaoActionPerformed(evt);
            }
        });

        checkDinamismo.setBackground(new java.awt.Color(255, 255, 255));
        checkDinamismo.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkDinamismo.setText("Dinamismo, Criatividade e Integridade Absolutas");
        checkDinamismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDinamismoActionPerformed(evt);
            }
        });

        checkMSOffice.setBackground(new java.awt.Color(255, 255, 255));
        checkMSOffice.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkMSOffice.setText("Excelente Domínio do Microsoft Office ");
        checkMSOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMSOfficeActionPerformed(evt);
            }
        });

        checkAdaptacaco.setBackground(new java.awt.Color(255, 255, 255));
        checkAdaptacaco.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkAdaptacaco.setText("Facilidade de se Adaptar ao Ambiente de Trabalho");
        checkAdaptacaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAdaptacacoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/add_user_group_woman_man_80px.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(checkDisponibilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkPressao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkDinamismo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkMSOffice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkEquipa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkAdaptacaco, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(checkDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkEquipa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkPressao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkDinamismo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkMSOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkAdaptacaco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(43, 43, 43))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkDisponibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDisponibilidadeActionPerformed
         maisPontos ++;
    }//GEN-LAST:event_checkDisponibilidadeActionPerformed

    private void checkEquipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEquipaActionPerformed
         maisPontos = pontosAux ++;
    }//GEN-LAST:event_checkEquipaActionPerformed

    private void checkPressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPressaoActionPerformed
         maisPontos ++;
    }//GEN-LAST:event_checkPressaoActionPerformed

    private void checkDinamismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDinamismoActionPerformed
         maisPontos ++;
    }//GEN-LAST:event_checkDinamismoActionPerformed

    private void checkMSOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMSOfficeActionPerformed
         maisPontos ++;
    }//GEN-LAST:event_checkMSOfficeActionPerformed

    private void checkAdaptacacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAdaptacacoActionPerformed
         maisPontos ++;
    }//GEN-LAST:event_checkAdaptacacoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
           /*if((jtfNome.getText().isEmpty() || jtfSenha.getText().isEmpty())){
               JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Atenção", INFORMATION_MESSAGE);
           } else {*/ 
               DAO dao = new DAO(); 
               CandidatosDao candidatoDao = new CandidatosDao(); 
               Candidato candidato = new Candidato();
               
               candidato.setNome(nomeAux);
               candidato.setIdade(idadeAux);
               candidato.setEstadoCivil(estadoCivilAux);
               candidato.setNrDocumento(nrDocumentoAux);
               candidato.setMorada(moradaAux);
               candidato.setEmail(emailAux);
               candidato.setNrCelular(contactoAux);
               candidato.setPontos(maisPontos);
               candidato.setNivelAcademico(nivelAcademicoAux);
               candidato.setCurso(cursoAux);
               
               candidatoDao.salvar(candidato);
               
              // preencherTabela(dao.listar(candidato));
           //}
        } catch (Exception ex) {
            Logger.getLogger(InternalVirtude.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   private String nomeAux, estadoCivilAux, nrDocumentoAux, moradaAux,  emailAux, 
           contactoAux, nivelAcademicoAux,  cursoAux;
   private int idadeAux, pontosAux;
   
   public void recebe (String nome, int idade, String estadoCivil, String nrDocumento, String morada,
            String email, String contacto, String nivelAcademico, String curso, int pontos){
       nomeAux = nome;
       idadeAux = idade;
       estadoCivilAux = estadoCivil;
       nrDocumentoAux = nrDocumento;
       moradaAux = morada;
       emailAux  =  email;
       contactoAux = contacto;
       cursoAux = curso;
       pontosAux = pontos;
    }

   private int maisPontos = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAdaptacaco;
    private javax.swing.JCheckBox checkDinamismo;
    private javax.swing.JCheckBox checkDisponibilidade;
    private javax.swing.JCheckBox checkEquipa;
    private javax.swing.JCheckBox checkMSOffice;
    private javax.swing.JCheckBox checkPressao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
