package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Clayd Nandza
 */
public class InternalQualificacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form Qualificacao
     */
    public InternalQualificacao() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI basicInternalFrameUi =(BasicInternalFrameUI)this.getUI();
        basicInternalFrameUi.setNorthPane(null);
        
        boxFormacao.setEnabled(false);
        boxLicenciatura.setEnabled(false);
        boxLMestrado.setEnabled(false);
        
        checkNivelMedio.setEnabled(false);
        checkFormacao.setEnabled(false);
        checkLicenciatura.setEnabled(false);
        checkMestrado.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkNivelMedio = new javax.swing.JCheckBox();
        checkNivelBasico = new javax.swing.JCheckBox();
        checkFormacao = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        boxFormacao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        checkMestrado = new javax.swing.JCheckBox();
        checkLicenciatura = new javax.swing.JCheckBox();
        boxLMestrado = new javax.swing.JComboBox<>();
        boxLicenciatura = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(940, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Condensed", 2, 30)); // NOI18N
        jLabel1.setText("   Certificacoes e Qualificaoes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/qualifications.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        jLabel5.setText("Qualificacoes Academicas");

        checkNivelMedio.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkNivelMedio.setText("Nivel Medio do SNE");
        checkNivelMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNivelMedioActionPerformed(evt);
            }
        });

        checkNivelBasico.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkNivelBasico.setText("Nivel Basico do SNE");
        checkNivelBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNivelBasicoActionPerformed(evt);
            }
        });

        checkFormacao.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkFormacao.setText("Formacao Profissional");
        checkFormacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFormacaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        jLabel3.setText("Formacao Profissional");

        boxFormacao.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        boxFormacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        jLabel4.setText("Formacao Superior");

        checkMestrado.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkMestrado.setText("Mestrado");
        checkMestrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMestradoActionPerformed(evt);
            }
        });

        checkLicenciatura.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        checkLicenciatura.setText("Licenciatura");
        checkLicenciatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLicenciaturaActionPerformed(evt);
            }
        });

        boxLMestrado.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        boxLMestrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        boxLicenciatura.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        boxLicenciatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("Clica na area de Linguas se tiver completado o registo das Certificacoes Academicas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkNivelBasico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(checkFormacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(checkLicenciatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(checkMestrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boxFormacao, 0, 170, Short.MAX_VALUE)
                                    .addComponent(boxLicenciatura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkNivelMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxLMestrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkNivelMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkNivelBasico, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxFormacao)
                            .addComponent(checkFormacao, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkLicenciatura, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxLicenciatura, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkMestrado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxLMestrado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkNivelMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNivelMedioActionPerformed
        checkLicenciatura.setEnabled(true);
        checkMestrado.setEnabled(false); 
        nivelAcademico = "Medio";
    }//GEN-LAST:event_checkNivelMedioActionPerformed

    private void checkNivelBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNivelBasicoActionPerformed
        checkFormacao.setEnabled(true);
        checkNivelMedio.setEnabled(true);
        checkLicenciatura.setEnabled(false);
        checkMestrado.setEnabled(false); 
        nivelAcademico = "Basico";
    }//GEN-LAST:event_checkNivelBasicoActionPerformed

    private void checkFormacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFormacaoActionPerformed
        checkLicenciatura.setEnabled(true);
        checkMestrado.setEnabled(false); 
        boxFormacao.setEnabled(true);
        curso = boxFormacao.getSelectedItem().toString();
        nivelAcademico = "Medio";
    }//GEN-LAST:event_checkFormacaoActionPerformed

    private void checkMestradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMestradoActionPerformed
        boxLMestrado.setEnabled(true);
        curso = boxLMestrado.getSelectedItem().toString();
        nivelAcademico = "Superior";
    }//GEN-LAST:event_checkMestradoActionPerformed

    private void checkLicenciaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLicenciaturaActionPerformed
        checkMestrado.setEnabled(true);
        boxLicenciatura.setEnabled(true);
        curso = boxLicenciatura.getSelectedItem().toString();
        nivelAcademico = "Superior";
    }//GEN-LAST:event_checkLicenciaturaActionPerformed
    
   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
   private String nomeAux, estadoCivilAux, nrDocumentoAux, moradaAux,  emailAux, contactoAux;
   private int idadeAux;
   
    public void recebe (String nome, int idade, String estadoCivil,  String nrDocumento, String morada,
            String email, String contacto){
       nomeAux = nome;
       idadeAux = idade;
       estadoCivilAux = estadoCivil;
       nrDocumentoAux = nrDocumento;
       moradaAux = morada;
       emailAux  =  email;
       contactoAux = contacto;
    }

    
  private  String nivelAcademico, curso;
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxFormacao;
    private javax.swing.JComboBox<String> boxLMestrado;
    private javax.swing.JComboBox<String> boxLicenciatura;
    private javax.swing.JCheckBox checkFormacao;
    private javax.swing.JCheckBox checkLicenciatura;
    private javax.swing.JCheckBox checkMestrado;
    private javax.swing.JCheckBox checkNivelBasico;
    private javax.swing.JCheckBox checkNivelMedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
