package view;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Clayd Nandza
 */
public class TelaMenu extends javax.swing.JFrame {

    private  Color corEntered = new Color(19,159,130);
    private Color corExited= new Color(255,255,255);
    /**
     * Creates new form TesteMenu
     */
    public TelaMenu() {
        initComponents();
        btnConfiguracoes.setEnabled(false);
        btnDocumentos.setEnabled(false);
        btnEstatisticas.setEnabled(false);
        btnNotificacoes.setEnabled(false);
        btnRelatorios.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCandidatos = new javax.swing.JButton();
        btnEmpregadores = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnDocumentos = new javax.swing.JButton();
        btnEstatisticas = new javax.swing.JButton();
        btnEncaminhamentos = new javax.swing.JButton();
        btnNotificacoes = new javax.swing.JButton();
        btnConfiguracoes = new javax.swing.JButton();
        btnVagas = new javax.swing.JButton();
        btnInformacao = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(170, 100));
        setResizable(false);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(0, 153, 204));
        jPanel12.setFont(new java.awt.Font("Serif", 2, 55)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Serif", 2, 36)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        btnCandidatos.setBackground(new java.awt.Color(255, 255, 255));
        btnCandidatos.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnCandidatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/candidatosi.png"))); // NOI18N
        btnCandidatos.setText("Gerir Candidatos");
        btnCandidatos.setIconTextGap(15);
        btnCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCandidatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCandidatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCandidatosMouseExited(evt);
            }
        });

        btnEmpregadores.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpregadores.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnEmpregadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/group_of_companies_50px.png"))); // NOI18N
        btnEmpregadores.setText("Empregadores");
        btnEmpregadores.setBorderPainted(false);
        btnEmpregadores.setIconTextGap(25);
        btnEmpregadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpregadoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpregadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpregadoresMouseExited(evt);
            }
        });

        btnFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        btnFuncionarios.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/add_user_group_woman_man_80px.png"))); // NOI18N
        btnFuncionarios.setText("Gerir Funcionarios");
        btnFuncionarios.setIconTextGap(6);
        btnFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseExited(evt);
            }
        });

        btnDocumentos.setBackground(new java.awt.Color(255, 255, 255));
        btnDocumentos.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/pdf_matte.png"))); // NOI18N
        btnDocumentos.setText("Documentos");
        btnDocumentos.setIconTextGap(6);
        btnDocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocumentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDocumentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDocumentosMouseExited(evt);
            }
        });

        btnEstatisticas.setBackground(new java.awt.Color(255, 255, 255));
        btnEstatisticas.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnEstatisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/Diagram_perspective_matter.png"))); // NOI18N
        btnEstatisticas.setText("Estatisticas");
        btnEstatisticas.setIconTextGap(8);
        btnEstatisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstatisticasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstatisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstatisticasMouseExited(evt);
            }
        });

        btnEncaminhamentos.setBackground(new java.awt.Color(255, 255, 255));
        btnEncaminhamentos.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnEncaminhamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/permanent_job_48px.png"))); // NOI18N
        btnEncaminhamentos.setText("Encaminhamentos");
        btnEncaminhamentos.setIconTextGap(6);
        btnEncaminhamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncaminhamentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEncaminhamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEncaminhamentosMouseExited(evt);
            }
        });

        btnNotificacoes.setBackground(new java.awt.Color(255, 255, 255));
        btnNotificacoes.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnNotificacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/google_alerts_48px.png"))); // NOI18N
        btnNotificacoes.setText("Notificacoes");
        btnNotificacoes.setIconTextGap(12);
        btnNotificacoes.setPreferredSize(new java.awt.Dimension(250, 70));
        btnNotificacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotificacoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNotificacoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNotificacoesMouseExited(evt);
            }
        });

        btnConfiguracoes.setBackground(new java.awt.Color(255, 255, 255));
        btnConfiguracoes.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/Tools_perspective_matte.png"))); // NOI18N
        btnConfiguracoes.setText("Configuracoes");
        btnConfiguracoes.setIconTextGap(6);
        btnConfiguracoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfiguracoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfiguracoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfiguracoesMouseExited(evt);
            }
        });

        btnVagas.setBackground(new java.awt.Color(255, 255, 255));
        btnVagas.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnVagas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/job_seeker_64px.png"))); // NOI18N
        btnVagas.setText("Vagas");
        btnVagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVagasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVagasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVagasMouseExited(evt);
            }
        });

        btnInformacao.setBackground(new java.awt.Color(255, 255, 255));
        btnInformacao.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnInformacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/sobre.png"))); // NOI18N
        btnInformacao.setText("Informacao");
        btnInformacao.setIconTextGap(12);
        btnInformacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInformacaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInformacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInformacaoMouseExited(evt);
            }
        });

        btnRelatorios.setBackground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/relatorio.png"))); // NOI18N
        btnRelatorios.setText("Relatorios");
        btnRelatorios.setIconTextGap(18);
        btnRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseExited(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/logout.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setIconTextGap(15);
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel13.setText("Menu Principal");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnEmpregadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(btnCandidatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnEncaminhamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(btnVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(btnEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRelatorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConfiguracoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(btnNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(381, 381, 381))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpregadores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncaminhamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCandidatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCandidatosMouseEntered
        btnCandidatos.setBackground(corEntered);
    }//GEN-LAST:event_btnCandidatosMouseEntered

    private void btnCandidatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCandidatosMouseExited
        btnCandidatos.setBackground(corExited);
    }//GEN-LAST:event_btnCandidatosMouseExited

    private void btnEmpregadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpregadoresMouseEntered
        btnEmpregadores.setBackground(corEntered);
    }//GEN-LAST:event_btnEmpregadoresMouseEntered

    private void btnEmpregadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpregadoresMouseExited
        btnEmpregadores.setBackground(corExited);
    }//GEN-LAST:event_btnEmpregadoresMouseExited

    private void btnFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseEntered
        btnFuncionarios.setBackground(corEntered);
    }//GEN-LAST:event_btnFuncionariosMouseEntered

    private void btnFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseExited
        btnFuncionarios.setBackground(corExited);
    }//GEN-LAST:event_btnFuncionariosMouseExited

    private void btnDocumentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentosMouseEntered
        btnDocumentos.setBackground(corEntered);
    }//GEN-LAST:event_btnDocumentosMouseEntered

    private void btnDocumentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentosMouseExited
        btnDocumentos.setBackground(corExited);
    }//GEN-LAST:event_btnDocumentosMouseExited

    private void btnEstatisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatisticasMouseEntered
        btnEstatisticas.setBackground(corEntered);
    }//GEN-LAST:event_btnEstatisticasMouseEntered

    private void btnEstatisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatisticasMouseExited
        btnEstatisticas.setBackground(corExited);
    }//GEN-LAST:event_btnEstatisticasMouseExited

    private void btnEncaminhamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncaminhamentosMouseEntered
        btnEncaminhamentos.setBackground(corEntered);
    }//GEN-LAST:event_btnEncaminhamentosMouseEntered

    private void btnEncaminhamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncaminhamentosMouseExited
        btnEncaminhamentos.setBackground(corExited);
    }//GEN-LAST:event_btnEncaminhamentosMouseExited

    private void btnNotificacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotificacoesMouseEntered
        btnNotificacoes.setBackground(corEntered);
    }//GEN-LAST:event_btnNotificacoesMouseEntered

    private void btnNotificacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotificacoesMouseExited
        btnNotificacoes.setBackground(corExited);
    }//GEN-LAST:event_btnNotificacoesMouseExited

    private void btnConfiguracoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracoesMouseEntered
        btnConfiguracoes.setBackground(corEntered);
    }//GEN-LAST:event_btnConfiguracoesMouseEntered

    private void btnConfiguracoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracoesMouseExited
        btnConfiguracoes.setBackground(corExited);
    }//GEN-LAST:event_btnConfiguracoesMouseExited

    private void btnVagasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVagasMouseEntered
        btnVagas.setBackground(corEntered);
    }//GEN-LAST:event_btnVagasMouseEntered

    private void btnVagasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVagasMouseExited
       btnVagas.setBackground(corExited);
    }//GEN-LAST:event_btnVagasMouseExited

    private void btnRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseEntered
        btnRelatorios.setBackground(corEntered);
    }//GEN-LAST:event_btnRelatoriosMouseEntered

    private void btnRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseExited
        btnRelatorios.setBackground(corExited);
    }//GEN-LAST:event_btnRelatoriosMouseExited

    private void btnInformacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacaoMouseEntered
        btnInformacao.setBackground(corEntered);
    }//GEN-LAST:event_btnInformacaoMouseEntered

    private void btnInformacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacaoMouseExited
        btnInformacao.setBackground(corExited);
    }//GEN-LAST:event_btnInformacaoMouseExited

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setBackground(corEntered);
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        btnSair.setBackground(corExited);
    }//GEN-LAST:event_btnSairMouseExited

    private void btnCandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCandidatosMouseClicked
        new TelaCandidatos().setVisible(true);
    }//GEN-LAST:event_btnCandidatosMouseClicked

    private void btnEmpregadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpregadoresMouseClicked
        new TelaEmpregadores().setVisible(true);
    }//GEN-LAST:event_btnEmpregadoresMouseClicked

    private void btnFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseClicked
        new TelaFuncionarios().setVisible(true);
    }//GEN-LAST:event_btnFuncionariosMouseClicked

    private void btnEncaminhamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncaminhamentosMouseClicked
        new TelaEncaminhamentos().setVisible(true);
    }//GEN-LAST:event_btnEncaminhamentosMouseClicked

    private void btnDocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentosMouseClicked
        new TelaDocumentos().setVisible(true);
    }//GEN-LAST:event_btnDocumentosMouseClicked

    private void btnEstatisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatisticasMouseClicked
        JOptionPane.showMessageDialog(null, "Funcao Indisponivel");
    }//GEN-LAST:event_btnEstatisticasMouseClicked

    private void btnNotificacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotificacoesMouseClicked
        JOptionPane.showMessageDialog(null, "Funcao Indisponivel");
    }//GEN-LAST:event_btnNotificacoesMouseClicked

    private void btnVagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVagasMouseClicked
        new TelaVaga().setVisible(true);
    }//GEN-LAST:event_btnVagasMouseClicked

    private void btnRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseClicked
        JOptionPane.showMessageDialog(null, "Funcao Indisponivel");
    }//GEN-LAST:event_btnRelatoriosMouseClicked

    private void btnConfiguracoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracoesMouseClicked
        new TelaAreas().setVisible(true);
    }//GEN-LAST:event_btnConfiguracoesMouseClicked

    private void btnInformacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacaoMouseClicked
        new TelaInformacao().setVisible(true);
    }//GEN-LAST:event_btnInformacaoMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
       dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidatos;
    private javax.swing.JButton btnConfiguracoes;
    private javax.swing.JButton btnDocumentos;
    private javax.swing.JButton btnEmpregadores;
    private javax.swing.JButton btnEncaminhamentos;
    private javax.swing.JButton btnEstatisticas;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnInformacao;
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVagas;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    // End of variables declaration//GEN-END:variables
}